# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', markitup.fields.MarkupField(no_rendered_field=True, verbose_name='Describe what your talk is about')),
                ('_abstract_rendered', models.TextField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talk_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Short_Talk'), ('L', 'Long_Talk'), ('T', 'Tutorial')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='talk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talks.Talk_Type'),
        ),
    ]
