# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:45
from __future__ import unicode_literals

from django.db import migrations
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='abstract',
            field=markitup.fields.MarkupField(help_text='Describe what your talk is about', no_rendered_field=True),
        ),
    ]
